using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;

namespace ClusterManager3000.Helper
{
    internal class HetznerServices
    {
        private readonly HttpClient httpClient = new HttpClient();
        private readonly AppConfiguration config = new AppConfiguration();

        public HetznerServices()
        {
            var apiKey = config.ApiKey;
            httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");
        }

        public async Task<string> GetServers()
        {
            using HttpResponseMessage
                response = await httpClient.GetAsync("https://api.hetzner.cloud/v1/servers");

            var message = await response.Content.ReadAsStringAsync();
            return message;
        }

        //TODO: Possible null-reference
        public async Task<string> GetServerByname(string serverName)
        {
            var servers = GetServers().Result;
            JObject jsonObject = JObject.Parse(servers);
            var item = jsonObject["servers"].FirstOrDefault(i => i["name"].ToString() == serverName);
            var serverId = item["id"].ToString();
            return serverId;
        }

        //TODO: make things variable for the server creation, like store server_type in config n stuff
        
        public async Task<string> CreateServer()
        {
            Random random = new Random();

            var servername = "eva" + config.Environment + random.Next(0, 1000);
            var sshKey = await CreateSshKey();

            if (sshKey == "failed") return "Failed Server Creation, SSHKey could not be created";

            using StringContent jsonContent = new(
                JsonSerializer.Serialize(new
                {
                    image = "ubuntu-24.04",
                    name = servername,
                    server_type = "cx22",
                    ssh_keys = new[] { sshKey }
                }),
                System.Text.Encoding.UTF8,
                "application/json");


            using HttpResponseMessage
                response = await httpClient.PostAsync("https://api.hetzner.cloud/v1/servers", jsonContent);

            var message = await response.Content.ReadAsStringAsync();
            return message;
        }

        public async Task DeleteServer(string id)
        {

            using HttpResponseMessage
                response = await httpClient.DeleteAsync($"https://api.hetzner.cloud/v1/servers/{id}");

            var message = await response.Content.ReadAsStringAsync();
        }

        //TODO: SSH key Should be autogenerated and saved in keystore or some safe file or az keyvault 
        public async Task<string> CreateSshKey()
        {
            var guid = Guid.NewGuid().ToString();

            using StringContent jsonContent = new(
                JsonSerializer.Serialize(new
                {
                    name = guid,
                    public_key = config.SshKey
                }),
                System.Text.Encoding.UTF8,
                "application/json");


            using HttpResponseMessage
                response = await httpClient.PostAsync("https://api.hetzner.cloud/v1/ssh_keys", jsonContent);

            var message = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode) return guid;
            else return "failed";
        }

    }
}
